<a href="https://colab.research.google.com/github/SChiu-project/reddit-NLP/blob/main/NQ_2018_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

20230620

In [ ]:
# import library
import datetime

import numpy as np
import pandas as pd
import math

import tensorflow as tf

from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
# pandas-datareader 多個數據源讀取金融數據的庫

import pandas_datareader as pdr

In [ ]:
# yfinance
import yfinance as yf

In [ ]:

# 從 Yahoo Finance 中讀取 S&P 500 的歷史價格

df_NQ = yf.download('^IXIC', start='2022-07-01', end='2023-07-01')
df_NQ

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2022-07-01,11006.830078,11132.549805,10922.709961,11127.849609,11127.849609,4865730000
2022-07-05,10964.179688,11323.889648,10911.450195,11322.240234,11322.240234,5053570000
2022-07-06,11337.900391,11443.150391,11250.320312,11361.849609,11361.849609,4851170000
2022-07-07,11422.599609,11644.469727,11412.879883,11621.349609,11621.349609,4685050000
2022-07-08,11503.610352,11689.700195,11479.769531,11635.309570,11635.309570,4526570000
...,...,...,...,...,...,...
2023-06-26,13468.740234,13573.570312,13334.419922,13335.780273,13335.780273,4430600000
2023-06-27,13389.250000,13578.799805,13366.969727,13555.669922,13555.669922,5053660000
2023-06-28,13506.019531,13654.139648,13495.730469,13591.750000,13591.750000,4533270000
2023-06-29,13592.360352,13618.530273,13540.259766,13591.330078,13591.330078,4388140000
2023-06-30,13719.980469,13816.679688,13716.160156,13787.919922,13787.919922,4661120000

In [ ]:
df_NQ.describe(include='all')

,Open,High,Low,Close,Adj Close,Volume
count,251.000000,251.000000,251.000000,251.000000,251.000000,2.510000e+02
mean,11714.171805,11822.737192,11616.425836,11728.021340,11728.021340,4.898696e+09
std,833.916587,826.634417,849.567562,843.213554,843.213554,7.174876e+08
min,10131.820312,10393.219727,10088.830078,10213.290039,10213.290039,2.184080e+09
25%,11048.089844,11201.304688,10979.229980,11121.000000,11121.000000,4.433565e+09
50%,11640.370117,11733.799805,11514.740234,11635.309570,11635.309570,4.792140e+09
75%,12185.360352,12238.369629,12084.544922,12195.135254,12195.135254,5.191510e+09
max,13859.070312,13864.059570,13716.160156,13787.919922,13787.919922,8.076530e+09

In [ ]:
df_NQ.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 251 entries, 2022-07-01 to 2023-06-30
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       251 non-null    float64
 1   High       251 non-null    float64
 2   Low        251 non-null    float64
 3   Close      251 non-null    float64
 4   Adj Close  251 non-null    float64
 5   Volume     251 non-null    int64
dtypes: float64(5), int64(1)
memory usage: 13.7 KB

In [ ]:

df_NQ['percent_chnage'] = (df_NQ['Close']/df_NQ['Open']-1)*100
df_NQ

,Open,High,Low,Close,Adj Close,Volume,percent_chnage
Date,,,,,,,
2022-07-01,11006.830078,11132.549805,10922.709961,11127.849609,11127.849609,4865730000,1.099495
2022-07-05,10964.179688,11323.889648,10911.450195,11322.240234,11322.240234,5053570000,3.265730
2022-07-06,11337.900391,11443.150391,11250.320312,11361.849609,11361.849609,4851170000,0.211232
2022-07-07,11422.599609,11644.469727,11412.879883,11621.349609,11621.349609,4685050000,1.739972
2022-07-08,11503.610352,11689.700195,11479.769531,11635.309570,11635.309570,4526570000,1.144851
...,...,...,...,...,...,...,...
2023-06-26,13468.740234,13573.570312,13334.419922,13335.780273,13335.780273,4430600000,-0.987174
2023-06-27,13389.250000,13578.799805,13366.969727,13555.669922,13555.669922,5053660000,1.242937
2023-06-28,13506.019531,13654.139648,13495.730469,13591.750000,13591.750000,4533270000,0.634757
2023-06-29,13592.360352,13618.530273,13540.259766,13591.330078,13591.330078,4388140000,-0.007580
2023-06-30,13719.980469,13816.679688,13716.160156,13787.919922,13787.919922,4661120000,0.495186

In [ ]:

df_NQ['Jump'] = np.where((df_NQ.percent_chnage>=0) & (1>df_NQ.percent_chnage) ,1,0)
df_NQ

,Open,High,Low,Close,Adj Close,Volume,percent_chnage,Jump
Date,,,,,,,,
2022-07-01,11006.830078,11132.549805,10922.709961,11127.849609,11127.849609,4865730000,1.099495,0
2022-07-05,10964.179688,11323.889648,10911.450195,11322.240234,11322.240234,5053570000,3.265730,0
2022-07-06,11337.900391,11443.150391,11250.320312,11361.849609,11361.849609,4851170000,0.211232,1
2022-07-07,11422.599609,11644.469727,11412.879883,11621.349609,11621.349609,4685050000,1.739972,0
2022-07-08,11503.610352,11689.700195,11479.769531,11635.309570,11635.309570,4526570000,1.144851,0
...,...,...,...,...,...,...,...,...
2023-06-26,13468.740234,13573.570312,13334.419922,13335.780273,13335.780273,4430600000,-0.987174,0
2023-06-27,13389.250000,13578.799805,13366.969727,13555.669922,13555.669922,5053660000,1.242937,0
2023-06-28,13506.019531,13654.139648,13495.730469,13591.750000,13591.750000,4533270000,0.634757,1
2023-06-29,13592.360352,13618.530273,13540.259766,13591.330078,13591.330078,4388140000,-0.007580,0
2023-06-30,13719.980469,13816.679688,13716.160156,13787.919922,13787.919922,4661120000,0.495186,1

In [ ]:
df_NQ['Big_Jump'] = np.where((df_NQ.percent_chnage>=1),1,0)
df_NQ

,Open,High,Low,Close,Adj Close,Volume,percent_chnage,Jump,Big_Jump
Date,,,,,,,,,
2022-07-01,11006.830078,11132.549805,10922.709961,11127.849609,11127.849609,4865730000,1.099495,0,1
2022-07-05,10964.179688,11323.889648,10911.450195,11322.240234,11322.240234,5053570000,3.265730,0,1
2022-07-06,11337.900391,11443.150391,11250.320312,11361.849609,11361.849609,4851170000,0.211232,1,0
2022-07-07,11422.599609,11644.469727,11412.879883,11621.349609,11621.349609,4685050000,1.739972,0,1
2022-07-08,11503.610352,11689.700195,11479.769531,11635.309570,11635.309570,4526570000,1.144851,0,1
...,...,...,...,...,...,...,...,...,...
2023-06-26,13468.740234,13573.570312,13334.419922,13335.780273,13335.780273,4430600000,-0.987174,0,0
2023-06-27,13389.250000,13578.799805,13366.969727,13555.669922,13555.669922,5053660000,1.242937,0,1
2023-06-28,13506.019531,13654.139648,13495.730469,13591.750000,13591.750000,4533270000,0.634757,1,0
2023-06-29,13592.360352,13618.530273,13540.259766,13591.330078,13591.330078,4388140000,-0.007580,0,0
2023-06-30,13719.980469,13816.679688,13716.160156,13787.919922,13787.919922,4661120000,0.495186,1,0

In [ ]:
df_NQ['Drop'] = np.where((df_NQ.percent_chnage<0) & (-1<df_NQ.percent_chnage) ,1,0)
df_NQ

,Open,High,Low,Close,Adj Close,Volume,percent_chnage,Jump,Big_Jump,Drop
Date,,,,,,,,,,
2022-07-01,11006.830078,11132.549805,10922.709961,11127.849609,11127.849609,4865730000,1.099495,0,1,0
2022-07-05,10964.179688,11323.889648,10911.450195,11322.240234,11322.240234,5053570000,3.265730,0,1,0
2022-07-06,11337.900391,11443.150391,11250.320312,11361.849609,11361.849609,4851170000,0.211232,1,0,0
2022-07-07,11422.599609,11644.469727,11412.879883,11621.349609,11621.349609,4685050000,1.739972,0,1,0
2022-07-08,11503.610352,11689.700195,11479.769531,11635.309570,11635.309570,4526570000,1.144851,0,1,0
...,...,...,...,...,...,...,...,...,...,...
2023-06-26,13468.740234,13573.570312,13334.419922,13335.780273,13335.780273,4430600000,-0.987174,0,0,1
2023-06-27,13389.250000,13578.799805,13366.969727,13555.669922,13555.669922,5053660000,1.242937,0,1,0
2023-06-28,13506.019531,13654.139648,13495.730469,13591.750000,13591.750000,4533270000,0.634757,1,0,0
2023-06-29,13592.360352,13618.530273,13540.259766,13591.330078,13591.330078,4388140000,-0.007580,0,0,1
2023-06-30,13719.980469,13816.679688,13716.160156,13787.919922,13787.919922,4661120000,0.495186,1,0,0

In [ ]:
df_NQ['Big_Drop'] = np.where((df_NQ.percent_chnage<=-1),1,0)
df_NQ

,Open,High,Low,Close,Adj Close,Volume,percent_chnage,Jump,Big_Jump,Drop,Big_Drop
Date,,,,,,,,,,,
2022-07-01,11006.830078,11132.549805,10922.709961,11127.849609,11127.849609,4865730000,1.099495,0,1,0,0
2022-07-05,10964.179688,11323.889648,10911.450195,11322.240234,11322.240234,5053570000,3.265730,0,1,0,0
2022-07-06,11337.900391,11443.150391,11250.320312,11361.849609,11361.849609,4851170000,0.211232,1,0,0,0
2022-07-07,11422.599609,11644.469727,11412.879883,11621.349609,11621.349609,4685050000,1.739972,0,1,0,0
2022-07-08,11503.610352,11689.700195,11479.769531,11635.309570,11635.309570,4526570000,1.144851,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2023-06-26,13468.740234,13573.570312,13334.419922,13335.780273,13335.780273,4430600000,-0.987174,0,0,1,0
2023-06-27,13389.250000,13578.799805,13366.969727,13555.669922,13555.669922,5053660000,1.242937,0,1,0,0
2023-06-28,13506.019531,13654.139648,13495.730469,13591.750000,13591.750000,4533270000,0.634757,1,0,0,0
2023-06-29,13592.360352,13618.530273,13540.259766,13591.330078,13591.330078,4388140000,-0.007580,0,0,1,0
2023-06-30,13719.980469,13816.679688,13716.160156,13787.919922,13787.919922,4661120000,0.495186,1,0,0,0

In [ ]:
df_NQ.describe(include='all')

,Open,High,Low,Close,Adj Close,Volume,percent_chnage,Jump,Big_Jump,Drop,Big_Drop
count,251.000000,251.000000,251.000000,251.000000,251.000000,2.510000e+02,251.000000,251.000000,251.000000,251.000000,251.000000
mean,11714.171805,11822.737192,11616.425836,11728.021340,11728.021340,4.898696e+09,0.121288,0.270916,0.270916,0.270916,0.187251
std,833.916587,826.634417,849.567562,843.213554,843.213554,7.174876e+08,1.283954,0.445321,0.445321,0.445321,0.390892
min,10131.820312,10393.219727,10088.830078,10213.290039,10213.290039,2.184080e+09,-3.922809,0.000000,0.000000,0.000000,0.000000
25%,11048.089844,11201.304688,10979.229980,11121.000000,11121.000000,4.433565e+09,-0.690171,0.000000,0.000000,0.000000,0.000000
50%,11640.370117,11733.799805,11514.740234,11635.309570,11635.309570,4.792140e+09,0.058841,0.000000,0.000000,0.000000,0.000000
75%,12185.360352,12238.369629,12084.544922,12195.135254,12195.135254,5.191510e+09,1.081074,1.000000,1.000000,1.000000,0.000000
max,13859.070312,13864.059570,13716.160156,13787.919922,13787.919922,8.076530e+09,5.105993,1.000000,1.000000,1.000000,1.000000

In [ ]:
df_NQ.to_csv("df_NQ.csv")